- name: Create proxy fiile 
  script: /tmp/dockerfile/create_proxy.sh creates=/tmp/dockerfile/myproxy

- block:
    - name: login to DockerHub remote registry using your account
      docker_login:
        username: "{{ docker_hub_uname }}"
        password: "{{ docker_hub_pass }}"
        email: "{{ docker_hub_email }}"

    - name: Build rproxy image
      docker_image: path="/tmp/dockerfile" name="tksarah/rproxy" state=present force=true

    - name: Run Reverse Proxy on my container
      docker_container:
        name: "rproxy"
        image: tksarah/rproxy
        detach: true
        state: started
        ports:
          - "80:80"
        tty: true
  tags: rproxy

- name: Clean up
  file: path="/tmp/dockerfile" state=absent

