- block:
    - name:  remove serverspec target container for "{{ t1name }}"
      docker_container:
        name: "{{ t1name }}"
        image: "tksarah/lesson_serverspec_target"
        state: absent

    - name: remove serverspec host container for "{{ h1name }}"
      docker_container:
        name: "{{ h1name }}"
        image: "tksarah/lesson_serverspec_host"
        state: absent

    - name: Delete "{{ user }}" user
      user: name="{{ user }}" state=absent remove=yes
